[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile

# NVM
export NVM_DIR="$HOME/.nvm"
# This loads nvm
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
# This loads nvm bash_completion
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# RVM
# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change
export PATH="$HOME/.rvm/bin:$PATH"

# Add Rust binaries to PATH
export PATH="$HOME/.cargo/bin:$PATH"
